# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-10-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28, unique='True')),
                ('content', models.CharField(max_length=60)),
                ('imgPath', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'search_content',
                'verbose_name_plural': 'search_content',
            },
        ),
        migrations.CreateModel(
            name='User_infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GENDER', models.CharField(max_length=20)),
                ('SCHOOL', models.CharField(max_length=16)),
                ('F_EDUCATION', models.CharField(max_length=16)),
                ('M_EDUCATION', models.CharField(max_length=16)),
                ('F_CAREER', models.CharField(max_length=16)),
                ('M_CAREER', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'User_infor',
                'verbose_name_plural': 'User_infor',
            },
        ),
    ]
