# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-10-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_content',
            name='title',
            field=models.CharField(max_length=28),
        ),
    ]
